### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by avalanche1** [zlatanvasovic/percent#3]
Hi! Could you plz add TS typings?
Thanks for the lib :)

**Comment by zdroid** [comment]
I guess I could, but I haven't really been involved with TypeScript so far. Can you give me an example of what you had in mind?

**Comment by avalanche1** [comment]
Actually, it's rather easy. Here's an example of typedef for a lib somewhat resembling yours - [is.js](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/is/index.d.ts)

**Comment by zdroid** [comment]
I am not sure how would this be useful for the project, as it seems to just add another layer of complexity. However, if you are willing to make a pull request for this, I'm also willing to accept it. :+1:

**Comment by avalanche1** [comment]
Well, nowadays adding typings to libs is a standard practice. Think about it.
And it doesnt add complexity - it adds to dev experience and less bugs when devving. Try typescript, it's awesome.

**Comment by zdroid** [comment]
I understood you well, I will consider this. I just don't see any direct benefit from this, as I have to change two files for every edit.
